### ISSUE TITLE
Unable to write a price

### ISSUE THREAD

**Issue by ekkis** [eostitan/delphioracle#11]
due to the other issue I opened: https://github.com/eostitan/delphioracle/issues/10 I commented out the check to try to force a write.  now I get another error
```
cleos push action delphioracle write '{"owner":"dextersysdao", "quotes": [{"value":58500,"pair":"eosusd"}]}' -p dextersysdao@active
```

> Error 3050003: eosio_assert_message assertion failure
> Error Details:
> assertion failure with message: pair not allowed
> pending console output: length 1quote 0 58500 eosusd

**Comment by systemzax** [comment]
Make sure you call the "configure" function first. This will add the 'eosusd' pair entry to the 'pairs' datatable, allowing oracles to push values for this pair.

Additional pairs can be added by calling the 'newbounty' function, then having oracles and custodians voting in favor of the new pair.

You can set the approval thresholds in the parameters of the configure action.

**Comment by ekkis** [comment]
ok.  I have no idea what all these parameters are and I don't find docs on it so I've just set them all to 0:
```bash
cleos push action delphioracle configure '{"datapoints_per_instrument": 0, "bars_per_instrument": 0, "vote_interval": 0, "write_cooldown": 0, "approver_threshold": 0, "approving_oracles_threshold": 0, "approving_custodians_threshold": 0, "minimum_rank": 0, "paid": 0, "min_bounty_delay": 0, "new_bounty_delay": 0}'
```
but when I execute the above it pukes with:

> Error 3015014: Pack data exception
> Error Details:
> Missing field 'g' in input object while processing struct 'configure'

as if it doesn't recognise the parameters I'm passing it

**Comment by ekkis** [comment]
also curious, is use of CONTRACT, ACTION and TABLE new or is it old?  I tag my actions with `[[eosio::action]]`

**Comment by ekkis** [comment]
I've added instructions to the README for how to do this
