### ISSUE TITLE
improve code

### ISSUE THREAD

**Issue by threadshare** [eostitan/delphioracle#3]
## old code  <function: update_eosusd_oracle>
```C++
//skip first 6 values
        auto itr = value_sorted.begin();
        itr++;
        itr++;
        itr++;
        itr++;
        itr++;

        //get next 9 values
        for (int i = 0; i<9;i++){
          itr++;
          avg+=itr->value;
        }
```

I think it's better by this way.  
## new code
```C++
        auto itr = value_sorted.begin();
        //skip first 6 values
        //get next 9 values
        for (int i = 0; i<9;i++){
          itr++;
          if (i>5) {
            // skip first 6 values
            avg+=itr->value;
          }
        }
```

**Comment by systemzax** [comment]
New method uses median, so this part changed a bit. I agree it improves readability of the code, but it probably slows it down, adding additional checks and variable initialization. As this function is being called every minute per assets pair (which could grow into the thousands eventually) per BP, it's better to keep it as streamlined and economical as possible in terms of CPU resources.
